# Generated by Django 5.0.2 on 2024-03-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0002_alter_borrowing_actual_return_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(blank=True),
        ),
    ]
